//go:build mage

// The library has no dependency outside the standard library, and this file
// keeps that true: it imports nothing from mage, so mage stays out of go.mod.
// The comment sits above the package clause on purpose — a doc comment here is
// printed on top of every target listing.

package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Default is the target mage runs when the command line names none.
var Default = Help

// mageVersion pins the mage the Help target calls back into. A pinned version
// resolves from the module cache, so the command works without the network
// after the first run.
const mageVersion = "github.com/magefile/mage@v1.17.2"

// Show the available targets
func Help() error {
	return run("go", "run", mageVersion, "-l")
}

// Run tests with race, shuffle and a coverage report
func Test() error {
	if err := run(
		"go", "test", "-race", "-count=1", "-shuffle=on", "-timeout=10m",
		"-coverprofile=coverage.out", "-covermode=atomic", "./...",
	); err != nil {
		return err
	}
	return run("go", "tool", "cover", "-html=coverage.out", "-o", "coverage.html")
}

// Run golangci-lint
func Lint() error {
	return run("golangci-lint", "run", "./...")
}

// Run govulncheck
func Vuln() error {
	return run("go", "run", "golang.org/x/vuln/cmd/govulncheck@latest", "./...")
}

// Compile the library
func Build() error {
	return run("go", "build", "./...")
}

// Run every example
func Examples() error {
	dirs, err := exampleDirs()
	if err != nil {
		return err
	}
	for i, dir := range dirs {
		if i > 0 {
			fmt.Println()
		}
		fmt.Printf("Running %s example...\n", filepath.Base(dir))
		if err := runIn(dir, "go", "run", "main.go"); err != nil {
			return fmt.Errorf("example %s: %w", dir, err)
		}
	}
	return nil
}

// Run go mod tidy on every module
func Tidy() error {
	dirs, err := moduleDirs()
	if err != nil {
		return err
	}
	for _, dir := range dirs {
		if err := runIn(dir, "go", "mod", "tidy"); err != nil {
			return err
		}
	}
	return nil
}

// Format the code
func Fmt() error {
	// goimports comes from the network rather than from PATH: an installed
	// copy is built against an older x/tools and refuses to parse the generic
	// methods of compose.go.
	steps := [][]string{
		{"go", "fmt", "./..."},
		{"go", "run", "golang.org/x/tools/cmd/goimports@latest", "-w", "."},
		{"gofmt", "-s", "-w", "."},
	}
	for _, step := range steps {
		if err := run(step[0], step[1:]...); err != nil {
			return err
		}
	}
	return nil
}

// Run lint, vuln and test
func Check() error {
	return serial(Lint, Vuln, Test)
}

// Run the CI pipeline locally: tidy, fmt, lint, vuln and test
func Ci() error {
	return serial(Tidy, Fmt, Lint, Vuln, Test)
}

// Regenerate docs/llms.md from go doc
func Docs() error {
	// gomarkdoc cannot parse a generic method, so the reference comes from
	// go doc.
	out, err := exec.Command("go", "doc", "-all", ".").Output()
	if err != nil {
		return fmt.Errorf("go doc -all: %w", err)
	}

	var b strings.Builder
	b.WriteString("<!-- Generated by `mage docs`. DO NOT EDIT. -->\n\n")
	b.WriteString("# API reference\n\n")
	b.WriteString("The package documentation, as `go doc -all` prints it. The same text is on\n")
	b.WriteString("[pkg.go.dev](https://pkg.go.dev/github.com/veggiemonk/workflow).\n\n")
	b.WriteString("```\n")
	b.Write(out)
	b.WriteString("```\n")

	if err := os.WriteFile(filepath.Join("docs", "llms.md"), []byte(b.String()), 0o644); err != nil {
		return err
	}

	fmt.Println("Documentation available at:")
	for _, line := range []string{
		"  - README.md (main documentation)",
		"  - docs/architecture.md (architecture overview)",
		"  - docs/best-practices.md (best practices guide)",
		"  - examples/ (working examples)",
		"  - docs/llms.md (generated API documentation for LLMs)",
	} {
		fmt.Println(line)
	}
	return nil
}

// Install the development tools on PATH
func InstallTools() error {
	tools := []string{
		"github.com/golangci/golangci-lint/cmd/golangci-lint@latest",
		"github.com/stacklok/frizbee@latest",
	}
	for _, tool := range tools {
		if err := run("go", "install", tool); err != nil {
			return err
		}
	}
	return nil
}

// Pin the GitHub Actions to a digest
func PinActions() error {
	return run("go", "run", "github.com/stacklok/frizbee@latest", "actions", ".github/workflows")
}

// Remove the build artefacts
func Clean() error {
	if err := run("go", "clean", "./..."); err != nil {
		return err
	}
	artefacts := []string{
		"coverage.out",
		"coverage.html",
		filepath.Join("examples", "advanced", "results.json"),
	}
	for _, path := range artefacts {
		if err := os.Remove(path); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	return nil
}

// serial runs the targets in order and stops at the first failure. It replaces
// mg.SerialDeps, which would need the mage module in go.mod.
func serial(targets ...func() error) error {
	for _, target := range targets {
		if err := target(); err != nil {
			return err
		}
	}
	return nil
}

// run runs a command in the repository root and streams its output. Every
// target must return the error it produces: a discarded error here silently
// turns a check into a no-op.
func run(cmd string, args ...string) error {
	return runIn("", cmd, args...)
}

// runIn runs a command in dir. Each example is its own module, so it is
// built from its own directory.
func runIn(dir, cmd string, args ...string) error {
	c := exec.Command(cmd, args...)
	c.Dir = dir
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	c.Stdin = os.Stdin
	return c.Run()
}

// exampleDirs lists the example modules, sorted by name. The list is read from
// the tree rather than written down, so a new example needs no edit here.
func exampleDirs() ([]string, error) {
	mods, err := filepath.Glob(filepath.Join("examples", "*", "go.mod"))
	if err != nil {
		return nil, err
	}
	dirs := make([]string, 0, len(mods))
	for _, mod := range mods {
		dirs = append(dirs, filepath.Dir(mod))
	}
	return dirs, nil
}

// moduleDirs lists every module of the repository: the library first, then the
// examples.
func moduleDirs() ([]string, error) {
	examples, err := exampleDirs()
	if err != nil {
		return nil, err
	}
	return append([]string{"."}, examples...), nil
}
