# Makefile for workflow project

.PHONY: test lint vuln build examples clean help docs

# Default target
help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  %-15s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

test: ## Run tests with coverage
	go test -race -count=1 -shuffle=on -timeout=10m -coverprofile=coverage.out -covermode=atomic ./...
	go tool cover -html=coverage.out -o coverage.html

lint: ## Run golangci-lint
	golangci-lint run ./...

vuln: ## Run govulncheck
	go run golang.org/x/vuln/cmd/govulncheck@latest ./...

build: ## Build the project
	go build ./...

examples: ## Run all examples
	@echo "Running basic example..."
	@cd examples/basic && go run main.go
	@echo "\n\nRunning CI/CD example..."
	@cd examples/cicd && go run main.go
	@echo "\n\nRunning middleware example..."
	@cd examples/middleware && go run main.go
	@echo "\n\nRunning advanced example..."
	@cd examples/advanced && go run main.go

tidy: ## Run go mod tidy on all modules
	go mod tidy
	cd examples/basic && go mod tidy
	cd examples/cicd && go mod tidy
	cd examples/middleware && go mod tidy
	cd examples/advanced && go mod tidy

clean: ## Clean build artifacts
	go clean ./...
	rm -f coverage.out coverage.html
	rm -f examples/advanced/results.json

fmt: ## Format code
	go fmt ./...
	goimports -w .
	gofmt -s -w .

check: lint vuln test ## Run all checks (lint + vuln + test)

docs: ## Generate documentation
	@# gomarkdoc cannot parse a generic method, so the reference comes from go doc.
	@{ \
		echo '<!-- Generated by `make docs`. DO NOT EDIT. -->'; \
		echo ''; \
		echo '# API reference'; \
		echo ''; \
		echo 'The package documentation, as `go doc -all` prints it. The same text is on'; \
		echo '[pkg.go.dev](https://pkg.go.dev/github.com/veggiemonk/workflow).'; \
		echo ''; \
		echo '```'; \
		go doc -all .; \
		echo '```'; \
	} > docs/llms.md
	@echo "Documentation available at:"
	@echo "  - README.md (main documentation)"
	@echo "  - docs/architecture.md (architecture overview)"
	@echo "  - docs/best-practices.md (best practices guide)"
	@echo "  - examples/ (working examples)"
	@echo "  - docs/llms.md (generated API documentation for LLMs)"

install-tools: ## Install development tools
	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
	go install github.com/stacklok/frizbee@latest

pin-actions: ## pin github actions
	go run github.com/stacklok/frizbee@latest actions .github/workflows

ci: tidy fmt lint vuln test ## Run CI pipeline locally

.DEFAULT_GOAL := help
